all:
	R CMD INSTALL pkg-source-files/rlang_0.4.5.tar.gz
	R CMD INSTALL pkg-source-files/glue_1.4.0.tar.gz
	R CMD INSTALL pkg-source-files/digest_0.6.25.tar.gz
	R CMD INSTALL pkg-source-files/ellipsis_0.3.0.tar.gz
	R CMD INSTALL pkg-source-files/vctrs_0.2.4.tar.gz
	R CMD INSTALL pkg-source-files/pkgconfig_2.0.3.tar.gz
	R CMD INSTALL pkg-source-files/utf8_1.1.4.tar.gz
	R CMD INSTALL pkg-source-files/fansi_0.4.1.tar.gz
	R CMD INSTALL pkg-source-files/crayon_1.3.4.tar.gz
	R CMD INSTALL pkg-source-files/assertthat_0.2.1.tar.gz
	R CMD INSTALL pkg-source-files/cli_2.0.2.tar.gz
	R CMD INSTALL pkg-source-files/pillar_1.4.3.tar.gz
	R CMD INSTALL pkg-source-files/magrittr_1.5.tar.gz
	R CMD INSTALL pkg-source-files/lifecycle_0.2.0.tar.gz
	R CMD INSTALL pkg-source-files/tibble_3.0.1.tar.gz
	R CMD INSTALL pkg-source-files/lazyeval_0.2.2.tar.gz
	R CMD INSTALL pkg-source-files/plogr_0.2.0.tar.gz
	R CMD INSTALL pkg-source-files/BH_1.72.0-3.tar.gz
	R CMD INSTALL pkg-source-files/purrr_0.3.4.tar.gz
	R CMD INSTALL pkg-source-files/tidyselect_1.0.0.tar.gz
	R CMD INSTALL pkg-source-files/Rcpp_1.0.4.6.tar.gz
	R CMD INSTALL pkg-source-files/R6_2.4.1.tar.gz
	R CMD INSTALL pkg-source-files/dplyr_0.8.5.tar.gz
	R CMD INSTALL pkg-source-files/ape_5.3.tar.gz
	R CMD INSTALL pkg-source-files/tidytree_0.3.3.tar.gz
	R CMD INSTALL pkg-source-files/scatterplot3d_0.3-41.tar.gz
	R CMD INSTALL pkg-source-files/plotrix_3.7-8.tar.gz
	R CMD INSTALL pkg-source-files/fastmatch_1.1-0.tar.gz
	R CMD INSTALL pkg-source-files/igraph_1.2.5.tar.gz
	R CMD INSTALL pkg-source-files/quadprog_1.5-8.tar.gz
	R CMD INSTALL pkg-source-files/phangorn_2.5.5.tar.gz
	R CMD INSTALL pkg-source-files/numDeriv_2016.8-1.1.tar.gz
	R CMD INSTALL pkg-source-files/mnormt_1.5-6.tar.gz
	R CMD INSTALL pkg-source-files/gtools_3.8.2.tar.gz
	R CMD INSTALL pkg-source-files/expm_0.999-4.tar.gz
	R CMD INSTALL pkg-source-files/combinat_0.0-8.tar.gz
	R CMD INSTALL pkg-source-files/coda_0.19-3.tar.gz
	R CMD INSTALL pkg-source-files/clusterGeneration_1.3.4.tar.gz
	R CMD INSTALL pkg-source-files/curl_4.3.tar.gz
	R CMD INSTALL pkg-source-files/magick_2.3.tar.gz
	R CMD INSTALL pkg-source-files/animation_2.6.tar.gz
	R CMD INSTALL pkg-source-files/maps_3.3.0.tar.gz
	R CMD INSTALL pkg-source-files/phytools_0.7-20.tar.gz
	R CMD INSTALL pkg-source-files/gtable_0.3.0.tar.gz
	R CMD INSTALL pkg-source-files/jsonlite_1.6.1.tar.gz
	R CMD INSTALL pkg-source-files/treeio_1.10.0.tar.gz
	R CMD INSTALL pkg-source-files/stringi_1.4.6.tar.gz
	R CMD INSTALL pkg-source-files/tidyr_1.0.2.tar.gz
	R CMD INSTALL pkg-source-files/BiocManager_1.30.10.tar.gz
	R CMD INSTALL pkg-source-files/rvcheck_0.1.8.tar.gz
	R CMD INSTALL pkg-source-files/withr_2.2.0.tar.gz
	R CMD INSTALL pkg-source-files/viridisLite_0.3.0.tar.gz
	R CMD INSTALL pkg-source-files/RColorBrewer_1.1-2.tar.gz
	R CMD INSTALL pkg-source-files/colorspace_1.4-1.tar.gz
	R CMD INSTALL pkg-source-files/munsell_0.5.0.tar.gz
	R CMD INSTALL pkg-source-files/labeling_0.3.tar.gz
	R CMD INSTALL pkg-source-files/farver_2.0.3.tar.gz
	R CMD INSTALL pkg-source-files/scales_1.1.0.tar.gz
	R CMD INSTALL pkg-source-files/praise_1.0.0.tar.gz
	R CMD INSTALL pkg-source-files/rstudioapi_0.11.tar.gz
	R CMD INSTALL pkg-source-files/backports_1.1.6.tar.gz
	R CMD INSTALL pkg-source-files/rprojroot_1.3-2.tar.gz
	R CMD INSTALL pkg-source-files/prettyunits_1.1.1.tar.gz
	R CMD INSTALL pkg-source-files/desc_1.2.0.tar.gz
	R CMD INSTALL pkg-source-files/ps_1.3.2.tar.gz
	R CMD INSTALL pkg-source-files/processx_3.4.2.tar.gz
	R CMD INSTALL pkg-source-files/callr_3.4.3.tar.gz
	R CMD INSTALL pkg-source-files/pkgbuild_1.0.6.tar.gz
	R CMD INSTALL pkg-source-files/pkgload_1.0.2.tar.gz
	R CMD INSTALL pkg-source-files/evaluate_0.14.tar.gz
	R CMD INSTALL pkg-source-files/testthat_2.3.2.tar.gz
	R CMD INSTALL pkg-source-files/isoband_0.2.1.tar.gz
	R CMD INSTALL pkg-source-files/ggplot2_3.3.0.tar.gz
	R CMD INSTALL pkg-source-files/ggtree_2.0.4.tar.gz
	R CMD INSTALL pkg-source-files/plyr_1.8.6.tar.gz
	R CMD INSTALL pkg-source-files/ggridges_0.5.2.tar.gz
	R CMD INSTALL pkg-source-files/gridGraphics_0.5-0.tar.gz
	R CMD INSTALL pkg-source-files/ggplotify_0.0.5.tar.gz
	R CMD INSTALL pkg-source-files/ggimage_0.2.8.tar.gz
	R CMD INSTALL pkg-source-files/stringr_1.4.0.tar.gz
	R CMD INSTALL pkg-source-files/data.tree_0.7.11.tar.gz
	R CMD INSTALL pkg-source-files/cowplot_1.0.0.tar.gz
	R CMD INSTALL pkg-source-files/patchwork_1.0.0.tar.gz
	R CMD INSTALL pkg-source-files/aplot_0.0.4.tar.gz
